#############################################################################
# Makefile for building: moonlight-qt
# Generated by qmake (3.1) (Qt 6.10.1)
# Project:  moonlight-qt.pro
# Template: subdirs
# Command: C:\Qt\6.10.1\msvc2022_64\bin\qmake6.exe -o Makefile moonlight-qt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\6.10.1\msvc2022_64\bin\qmake6.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\6.10.1\msvc2022_64\bin\qmake6.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\6.10.1\msvc2022_64\bin\qmake6.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-moonlight-common-c \
		sub-qmdnsengine \
		sub-app \
		sub-h264bitstream \
		sub-AntiHooking


sub-moonlight-common-c-qmake_all:  FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	cd moonlight-common-c\ && $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && $(MAKE) -f Makefile qmake_all
sub-moonlight-common-c: $(MAKEFILE) FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile
sub-moonlight-common-c-make_first: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile 
sub-moonlight-common-c-all: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile all
sub-moonlight-common-c-clean: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile clean
sub-moonlight-common-c-distclean: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile distclean
sub-moonlight-common-c-install_subtargets: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile install
sub-moonlight-common-c-uninstall_subtargets: FORCE
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile uninstall
sub-qmdnsengine-qmake_all:  FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	cd qmdnsengine\ && $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && $(MAKE) -f Makefile qmake_all
sub-qmdnsengine: $(MAKEFILE) FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile
sub-qmdnsengine-make_first: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile 
sub-qmdnsengine-all: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile all
sub-qmdnsengine-clean: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile clean
sub-qmdnsengine-distclean: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile distclean
sub-qmdnsengine-install_subtargets: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile install
sub-qmdnsengine-uninstall_subtargets: FORCE
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-qmdnsengine-qmake_all sub-moonlight-common-c-qmake_all sub-h264bitstream-qmake_all sub-AntiHooking-qmake_all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: $(MAKEFILE) sub-qmdnsengine \
		sub-moonlight-common-c \
		sub-h264bitstream \
		sub-AntiHooking FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile
sub-app-make_first: sub-qmdnsengine-make_first sub-moonlight-common-c-make_first sub-h264bitstream-make_first sub-AntiHooking-make_first FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile 
sub-app-all: sub-qmdnsengine-all sub-moonlight-common-c-all sub-h264bitstream-all sub-AntiHooking-all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile all
sub-app-clean: sub-qmdnsengine-clean sub-moonlight-common-c-clean sub-h264bitstream-clean sub-AntiHooking-clean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile clean
sub-app-distclean: sub-qmdnsengine-distclean sub-moonlight-common-c-distclean sub-h264bitstream-distclean sub-AntiHooking-distclean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets: sub-qmdnsengine-install_subtargets sub-moonlight-common-c-install_subtargets sub-h264bitstream-install_subtargets sub-AntiHooking-install_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets: sub-qmdnsengine-uninstall_subtargets sub-moonlight-common-c-uninstall_subtargets sub-h264bitstream-uninstall_subtargets sub-AntiHooking-uninstall_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile uninstall
sub-h264bitstream-qmake_all:  FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	cd h264bitstream\ && $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && $(MAKE) -f Makefile qmake_all
sub-h264bitstream: $(MAKEFILE) FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile
sub-h264bitstream-make_first: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile 
sub-h264bitstream-all: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile all
sub-h264bitstream-clean: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile clean
sub-h264bitstream-distclean: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile distclean
sub-h264bitstream-install_subtargets: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile install
sub-h264bitstream-uninstall_subtargets: FORCE
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile uninstall
sub-AntiHooking-qmake_all:  FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	cd AntiHooking\ && $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && $(MAKE) -f Makefile qmake_all
sub-AntiHooking: $(MAKEFILE) FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile
sub-AntiHooking-make_first: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile 
sub-AntiHooking-all: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile all
sub-AntiHooking-clean: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile clean
sub-AntiHooking-distclean: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile distclean
sub-AntiHooking-install_subtargets: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile install
sub-AntiHooking-uninstall_subtargets: FORCE
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile uninstall

Makefile: moonlight-qt.pro .qmake.cache C:\Qt\6.10.1\msvc2022_64\mkspecs\win32-msvc\qmake.conf C:\Qt\6.10.1\msvc2022_64\mkspecs\features\spec_pre.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\common\windows-desktop.conf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\qconfig.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_ffmpegmediapluginimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssynchronizer.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssynchronizer_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediatestlibprivate_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlformat_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickeffects.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickshapesdesignhelpers_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagehelpers.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagehelpers_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testinternals_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequick.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequick_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qt_functions.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qt_config.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\spec_post.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\common\msvc-version.conf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\toolchain.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\default_pre.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\configure_base.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\configure.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\resolve_config.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\default_post.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\precompile_header.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\warn_on.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qmake_use.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\file_copies.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\windows.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exceptions.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\yacc.prf \
		C:\Qt\6.10.1\msvc2022_64\mkspecs\features\lex.prf \
		moonlight-qt.pro
	$(QMAKE) -o Makefile moonlight-qt.pro
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\spec_pre.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\common\windows-desktop.conf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\qconfig.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_ffmpegmediapluginimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssynchronizer.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labssynchronizer_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediatestlibprivate_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlformat_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickeffects.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickshapesdesignhelpers_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagehelpers.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagehelpers_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testinternals_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequick.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequick_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qt_functions.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qt_config.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\spec_post.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\common\msvc-version.conf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\toolchain.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\default_pre.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\configure_base.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\configure.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\resolve_config.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\default_post.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\precompile_header.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\warn_on.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\qmake_use.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\file_copies.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\win32\windows.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\testcase_targets.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\exceptions.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\yacc.prf:
C:\Qt\6.10.1\msvc2022_64\mkspecs\features\lex.prf:
moonlight-qt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile moonlight-qt.pro

qmake_all: sub-moonlight-common-c-qmake_all sub-qmdnsengine-qmake_all sub-app-qmake_all sub-h264bitstream-qmake_all sub-AntiHooking-qmake_all FORCE

make_first: sub-moonlight-common-c-make_first sub-qmdnsengine-make_first sub-app-make_first sub-h264bitstream-make_first sub-AntiHooking-make_first  FORCE
all: sub-moonlight-common-c-all sub-qmdnsengine-all sub-app-all sub-h264bitstream-all sub-AntiHooking-all  FORCE
clean: sub-moonlight-common-c-clean sub-qmdnsengine-clean sub-app-clean sub-h264bitstream-clean sub-AntiHooking-clean  FORCE
distclean: sub-moonlight-common-c-distclean sub-qmdnsengine-distclean sub-app-distclean sub-h264bitstream-distclean sub-AntiHooking-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-moonlight-common-c-install_subtargets sub-qmdnsengine-install_subtargets sub-app-install_subtargets sub-h264bitstream-install_subtargets sub-AntiHooking-install_subtargets FORCE
uninstall_subtargets: sub-moonlight-common-c-uninstall_subtargets sub-qmdnsengine-uninstall_subtargets sub-app-uninstall_subtargets sub-h264bitstream-uninstall_subtargets sub-AntiHooking-uninstall_subtargets FORCE

sub-moonlight-common-c-debug:
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile debug
sub-qmdnsengine-debug:
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile debug
sub-app-debug: sub-qmdnsengine-debug sub-moonlight-common-c-debug sub-h264bitstream-debug sub-AntiHooking-debug
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile debug
sub-h264bitstream-debug:
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile debug
sub-AntiHooking-debug:
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile debug
debug: sub-moonlight-common-c-debug sub-qmdnsengine-debug sub-app-debug sub-h264bitstream-debug sub-AntiHooking-debug

sub-moonlight-common-c-release:
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile release
sub-qmdnsengine-release:
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile release
sub-app-release: sub-qmdnsengine-release sub-moonlight-common-c-release sub-h264bitstream-release sub-AntiHooking-release
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile release
sub-h264bitstream-release:
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile release
sub-AntiHooking-release:
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile release
release: sub-moonlight-common-c-release sub-qmdnsengine-release sub-app-release sub-h264bitstream-release sub-AntiHooking-release

sub-moonlight-common-c-check:
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile check
sub-qmdnsengine-check:
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile check
sub-app-check: sub-qmdnsengine-check sub-moonlight-common-c-check sub-h264bitstream-check sub-AntiHooking-check
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile check
sub-h264bitstream-check:
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile check
sub-AntiHooking-check:
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile check
check: sub-moonlight-common-c-check sub-qmdnsengine-check sub-app-check sub-h264bitstream-check sub-AntiHooking-check

sub-moonlight-common-c-benchmark:
	@if not exist moonlight-common-c\ mkdir moonlight-common-c\ & if not exist moonlight-common-c\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd moonlight-common-c\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\moonlight-common-c\moonlight-common-c.pro ) && $(MAKE) -f Makefile benchmark
sub-qmdnsengine-benchmark:
	@if not exist qmdnsengine\ mkdir qmdnsengine\ & if not exist qmdnsengine\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd qmdnsengine\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\qmdnsengine\qmdnsengine.pro ) && $(MAKE) -f Makefile benchmark
sub-app-benchmark: sub-qmdnsengine-benchmark sub-moonlight-common-c-benchmark sub-h264bitstream-benchmark sub-AntiHooking-benchmark
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\app\app.pro ) && $(MAKE) -f Makefile benchmark
sub-h264bitstream-benchmark:
	@if not exist h264bitstream\ mkdir h264bitstream\ & if not exist h264bitstream\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd h264bitstream\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\h264bitstream\h264bitstream.pro ) && $(MAKE) -f Makefile benchmark
sub-AntiHooking-benchmark:
	@if not exist AntiHooking\ mkdir AntiHooking\ & if not exist AntiHooking\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd AntiHooking\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Maroun\Documents\Projects\moonlight-qt\AntiHooking\AntiHooking.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-moonlight-common-c-benchmark sub-qmdnsengine-benchmark sub-app-benchmark sub-h264bitstream-benchmark sub-AntiHooking-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

